from distutils.core import setup
from Chessmemory.utils import get_version

setup(name="chessmemory",
    version=get_version(),
    author="btrent",
    author_email="btrent@drinkngames.com",
    url="https://github.com/btrent/chessmemory",
    license="GNU GPL v2 and above",
    packages=["Chessmemory"],
    data_files=[
        ("share/chessmemory/images/", 
            ["data/images/black-bishop.png",
            "data/images/black-king.png",
            "data/images/black-knight.png",
            "data/images/black-pawn.png",
            "data/images/black-queen.png",
            "data/images/black-rook.png",
            "data/images/white-bishop.png",
            "data/images/white-king.png",
            "data/images/white-knight.png",
            "data/images/white-pawn.png",
            "data/images/white-queen.png",
            "data/images/white-rook.png",
            "data/images/white-bishop.png",
            "data/images/light-square.png",
            "data/images/dark-square.png",
            "data/images/border.png",
            "data/eco.positions",
            ]),
        ("share/pixmaps/", ["data/chessmemory.svg"]),
        ("share/applications/", ["data/chessmemory.desktop"]),
        ("share/chessmemory/", ["data/chessmemory.glade"]),
        ("share/chessmemory/", ["data/eco.positions"]),
    ],
    scripts=["chessmemory"],)
